service: clambda-av

custom:
  source_bucket: 'clambda-av-files'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  ecr:
    images:
      clambda-av:
        path: ./
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:PutObjectTagging'
        - 's3:GetObject'
      Resource: "arn:aws:s3:::*/*"
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource: "arn:aws:s3:::*"

functions:
  virusScan:
    image:
      name: clambda-av
    memorySize: 2048
    events:
      - s3: 
          bucket: clambda-av-files
          event: s3:ObjectCreated:*
    timeout: 120

package:
  exclude:
    - node_modules/**
    - coverage/**